#!/bin/bash
# set environment for all in this group
PATH=/usr/local/abin:$PATH

PG_VERSION=9.4
PG_HOME="/var/lib/postgresql"
PG_CONFDIR="/etc/postgresql/${PG_VERSION}/main"
PG_BINDIR="/usr/lib/postgresql/${PG_VERSION}/bin"
PG_DATADIR="${PG_HOME}/${PG_VERSION}/main"
PSQL_TRUST_LOCALNET=true

export PG_VERSION PG_HOME PG_CONFDIR PG_BINDIR PG_DATADIR PSQL_TRUST_LOCALNET

DB_NAME=autobahn
DB_USER=autouser
DB_PASS=123test

export DB_NAME DB_USER DB_PASS

set -o vi
